### ISSUE TITLE
Detect current boot device

### ISSUE THREAD

**Issue by matthiasg** [calmh/smartos-platform-upgrade#34]
Is there a way to include a way or at least a comment in the help to figure out what the current USB boot device is (the one mounted to /usbkey) ?

**Comment by liv3010m** [comment]
@matthiasg you can see your disks with the diskinfo command.
Lets say:
`$ diskinfo `
`TYPE    DISK                    VID      PID              SIZE          RMV SSD`
`SCSI    c1t0d0                  VMware   Virtual disk        1.86 GiB   no  no `
`SATA    c2t0d0                  ATA      ST8000VN0022-2EL112 7452.04 GiB   no  no`
...
If it's a USB stick it should say USB on the type column.
In my case it's c1t0d0 because it's a virtual disk (vmdk)
Thereafter I can run
`/opt/local/bin/platform-upgrade /dev/dsk/c1t0d0s1` or 
`/opt/local/bin/platform-upgrade /dev/dsk/c1t0d0s2` for a GPT partitioned disk.

Olivia

**Comment by matthiasg** [comment]
Yes, but that will list all USB devices . We always have two sticks in the system, both with smartos , is there a way to detect from within smartos which was booted of ?
